#Python 기초

In [ ]:
course_list = ["Python Basic", "Java Basic",
             "Python Machine Learning",
             "Java Web Development",
             "Embedded Programming with C++",
             "Data Science with Python",
             "Python Web Development",
             "Game Programming with Unity"]

In [ ]:
print(*enumerate(course_list))
# enumerate는 포인터 형식으로 반환

(0, 'Python Basic') (1, 'Java Basic') (2, 'Python Machine Learning') (3, 'Java Web Development') (4, 'Embedded Programming with C++') (5, 'Data Science with Python') (6, 'Python Web Development') (7, 'Game Programming with Unity')


In [ ]:
for index, course in enumerate(course_list):
    print(index, course)

0 Python Basic
1 Java Basic
2 Python Machine Learning
3 Java Web Development
4 Embedded Programming with C++
5 Data Science with Python
6 Python Web Development
7 Game Programming with Unity


In [ ]:
# dict에서 key와 value는 dict_key, dict_value 자료형이기에 list로 바꿔줘야함
course_dict = {
  "name": "Python Programming",
  "level":  "entry",
  "Price": 49900,
  "Rating": 4.98
}

In [ ]:
print(type(course_dict.keys()))
print(type(course_dict.values()))

key_list = list(course_dict.keys())
value_list = list(course_dict.values())

print(key_list, type(key_list))
print(value_list, type(value_list))

<class 'dict_keys'>
<class 'dict_values'>
['name', 'level', 'Price', 'Rating'] <class 'list'>
['Python Programming', 'entry', 49900, 4.98] <class 'list'>


In [ ]:
#.get method는 해당하는 값이 없으면 None을 반환
# list엔 없다네요^^
print(course_dict.get("including"))
print(course_dict.get("name"))

None
Python Programming


#NumPy

In [ ]:
import numpy as np

In [ ]:
data = [10, 20, 30]
arr = np.array(data)

print(arr.dtype)
print(arr.shape)
print(arr.size)

int64
(3,)
3


In [ ]:
data = [[10, 20, 30],[40,50,60]]
arr = np.array(data)

print(arr,"\n")
print(arr.dtype)
print(arr.shape)
print(arr.size)

[[10 20 30]
 [40 50 60]] 

int64
(2, 3)
6


In [ ]:
data = [[10, 20, 30],[40,50,60]]
arr = np.array(object=data, dtype = float)

print(arr,"\n")
print(arr.dtype)
print(arr.shape)
print(arr.size)

[[10. 20. 30.]
 [40. 50. 60.]] 

float64
(2, 3)
6


In [ ]:
data = [[[1,2,3],
          [4,5,6]],
        [[3,2,1],
         [6,5,4]]]

arr = np.array(data)

print(arr, '\n')
print(arr.dtype)
print(arr.shape)
print(arr.size)

[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [6 5 4]]] 

int64
(2, 2, 3)
12


In [ ]:
# zeros와 같은 함수는 argument를 tuple로 제공해야함
np.empty((3,5,6))

array([[[4.75468684e-316, 0.00000000e+000, 3.29047720e-321,
                     nan, 4.78829649e-317, 0.00000000e+000],
        [7.37108455e-260, 2.99484325e+262, 4.93432793e+257,
         9.13608697e+242, 5.83439516e+252, 1.50589683e+161],
        [2.02764139e+174, 9.08366784e+223, 2.62785629e+092,
         7.26612782e+223, 4.76660077e+180, 8.42961547e+252],
        [5.25478589e-091, 4.82336277e+228, 2.59345432e+161,
         1.71071858e+214, 3.67857957e+193, 4.82653073e+199],
        [2.13945865e+161, 1.43045919e+248, 4.78179653e+180,
         1.23542250e-259, 9.23546148e+242, 2.52960802e-258]],

       [[4.47593804e-091, 2.44041296e-154, 1.76353931e-070,
         8.63819469e-096, 7.12930810e+159, 2.61191759e+209],
        [6.01347002e-154, 1.66041816e+243, 7.26607075e+223,
         2.59345433e+161, 6.01334434e-154, 1.06441859e+248],
        [4.47590761e-091, 6.01334512e-154, 2.93282800e+222,
         2.46816475e-154, 5.28400063e+005, 1.90118402e-094],
        [8.89492561e+252, 2.59

In [ ]:
# ndarray인자를 안넣어도 된다
data = [[1,2,3],[4,5,6]]
one_array = np.ones_like(data)

print(data, type(data))
print()
print(one_array, type(one_array))

[[1, 2, 3], [4, 5, 6]] <class 'list'>

[[1 1 1]
 [1 1 1]] <class 'numpy.ndarray'>


In [ ]:
# 특정 타입 변경 method astype
origin = np.arange(1,2,0.2)
change = origin.astype(int)

print(origin)
print(change)

[1.  1.2 1.4 1.6 1.8]
[1 1 1 1 1]


In [ ]:
origin = np.arange(20)
print(origin)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
change1 = origin.reshape(2,2,5)
print(change1)

change2 = np.reshape(origin,(-1,2,5))
print(change2)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [ ]:
print(change)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [ ]:
change = origin.reshape(2,2,5)

print(change.sum(axis=0))
print()
print(change.sum(axis=1))
print()
print(change.sum(axis=2))

[[10 12 14 16 18]
 [20 22 24 26 28]]

[[ 5  7  9 11 13]
 [25 27 29 31 33]]

[[10 35]
 [60 85]]


In [ ]:
print(change)
print("-------------------------")
print(np.sort(change, axis=0)[::-1,:,:])
print("-------------------------")
print(np.sort(change, axis=0)[:,::-1,:])
print("-------------------------")
print(np.sort(change, axis=0)[:,:,::-1])
print("-------------------------")

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
-------------------------
[[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[ 0  1  2  3  4]
  [ 5  6  7  8  9]]]
-------------------------
[[[ 5  6  7  8  9]
  [ 0  1  2  3  4]]

 [[15 16 17 18 19]
  [10 11 12 13 14]]]
-------------------------
[[[ 4  3  2  1  0]
  [ 9  8  7  6  5]]

 [[14 13 12 11 10]
  [19 18 17 16 15]]]
-------------------------


In [ ]:
arr2 = origin.reshape(4,5)

In [ ]:
print(arr2,'\n')
print(np.sort(arr2, axis=0)[::-1,:],'\n')
print(np.sort(arr2, axis=1)[:,::-1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]] 

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]


In [ ]:
name = np.array(['John', 'Samuel', 'Kate', 'Mike', 'Sarah'])
score = np.array([78, 84, 96, 88, 82])

In [ ]:
sort_indexes = np.argsort(score)
print(sort_indexes)
print(name[sort_indexes])

[0 4 1 3 2]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


#Pandas

##Series

In [ ]:
import pandas as pd

In [ ]:
year = [2019, 2020, 2021, 2022]
result = pd.Series(year)

print(type(result))
print(result)

<class 'pandas.core.series.Series'>
0    2019
1    2020
2    2021
3    2022
dtype: int64


In [ ]:
year=[2019,2020,2021,2022]
idx=['a','b','c','d']

result = pd.Series(data= year, index=idx, name ='Year')
print(result)

a    2019
b    2020
c    2021
d    2022
Name: Year, dtype: int64


In [ ]:
score = {'kim': 80,
         'han':85,
         'Lee':90,
         'Choi':95}

result = pd.Series(data=score, name='score')
print(result)

kim     80
han     85
Lee     90
Choi    95
Name: score, dtype: int64


In [ ]:
print(result.index)
print(result.values)
print(result.dtype)
print(result.name)
print(result.index.name)

Index(['kim', 'han', 'Lee', 'Choi'], dtype='object')
[80 85 90 95]
int64
score
None


In [ ]:
result.name ='happy'
result.index.name = 'No'

print(result)

No
kim     80
han     85
Lee     90
Choi    95
Name: happy, dtype: int64


##DataFrame

In [ ]:
score = {'name': ['Jessi', 'Emma', 'Alex', 'Tom'],
         'score': [100,95,80,85],
         'grade': ['A','A','B','B']}

result = pd.DataFrame(score)
print(result)

    name  score grade
0  Jessi    100     A
1   Emma     95     A
2   Alex     80     B
3    Tom     85     B


In [ ]:
print(result)
idx = result['score'].argsort()
print(idx)
print(np.sort(result['score']))
print()
print(result['name'][idx])

    name  score grade
0  Jessi    100     A
1   Emma     95     A
2   Alex     80     B
3    Tom     85     B
0    2
1    3
2    1
3    0
Name: score, dtype: int64
[ 80  85  95 100]

2     Alex
3      Tom
1     Emma
0    Jessi
Name: name, dtype: object


In [ ]:
print(result.index)
print()
print(result.columns)
print()
print(result.values)
print()
print(result.dtypes)
print()
print(result.shape)

RangeIndex(start=0, stop=4, step=1)

Index(['name', 'score', 'grade'], dtype='object')

[['Jessi' 100 'A']
 ['Emma' 95 'A']
 ['Alex' 80 'B']
 ['Tom' 85 'B']]

name     object
score     int64
grade    object
dtype: object

(4, 3)


In [ ]:
result['subject']=['python','java','python','C']

In [ ]:
result

name  score grade subject
0  Jessi    100     A  python
1   Emma     95     A    java
2   Alex     80     B  python
3    Tom     85     B       C

In [ ]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   name     4 non-null      object
 1   score    4 non-null      int64 
 2   grade    4 non-null      object
 3   subject  4 non-null      object
dtypes: int64(1), object(3)
memory usage: 260.0+ bytes


In [ ]:
# frac은 sample에서만 됨
result.sample(frac=0.5)

name  score grade subject
0  Jessi    100     A  python
1   Emma     95     A    java

In [ ]:
result['age']=np.random.randint(low=20, high=25, size=4)

In [ ]:
result

name  score grade subject  age
0  Jessi    100     A  python   24
1   Emma     95     A    java   23
2   Alex     80     B  python   24
3    Tom     85     B       C   23

In [ ]:
# 범주형 데이터 확인
result.describe(include='object')


name grade subject
count       4     4       4
unique      4     2       3
top     Jessi     A  python
freq        1     2       2

In [ ]:
# 전체 데이터 확인
result.describe(include='all')

name       score grade subject       age
count       4    4.000000     4       4   4.00000
unique      4         NaN     2       3       NaN
top     Jessi         NaN     A  python       NaN
freq        1         NaN     2       2       NaN
mean      NaN   90.000000   NaN     NaN  23.50000
std       NaN    9.128709   NaN     NaN   0.57735
min       NaN   80.000000   NaN     NaN  23.00000
25%       NaN   83.750000   NaN     NaN  23.00000
50%       NaN   90.000000   NaN     NaN  23.50000
75%       NaN   96.250000   NaN     NaN  24.00000
max       NaN  100.000000   NaN     NaN  24.00000

In [ ]:
result['subject'].unique()

array(['python', 'java', 'C'], dtype=object)

In [ ]:
result['subject'].value_counts(normalize=True)

subject
python    0.50
java      0.25
C         0.25
Name: proportion, dtype: float64

In [ ]:
core = {'name': ['Jessi', 'Emma', 'Alex', 'Jessi', 'Tom'],
         'score': [100, 95, 80, 85, 97],
         'grade': ['A', 'A', 'B', 'B', 'A'],
         'subject': ['python', 'java', 'python', 'c', 'java']}

c = ['name', 'subject', 'score', 'grade', 'etc']

df = pd.DataFrame(data=core, columns=c)
print(df)

    name subject  score grade  etc
0  Jessi  python    100     A  NaN
1   Emma    java     95     A  NaN
2   Alex  python     80     B  NaN
3  Jessi       c     85     B  NaN
4    Tom    java     97     A  NaN


In [ ]:
want_col = ['name','subject','grade']
want_col_df = df[want_col]
want_col_df

name subject grade
0  Jessi  python     A
1   Emma    java     A
2   Alex  python     B
3  Jessi       c     B
4    Tom    java     A

In [ ]:
want_col_df['etc']=0

<ipython-input-154-f486f1beb9bc>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  want_col_df['etc']=0


In [ ]:
df

name subject  score grade  etc
0  Jessi  python    100     A  NaN
1   Emma    java     95     A  NaN
2   Alex  python     80     B  NaN
3  Jessi       c     85     B  NaN
4    Tom    java     97     A  NaN

In [ ]:
df['etc']=0
df

name subject  score grade  etc
0  Jessi  python    100     A    0
1   Emma    java     95     A    0
2   Alex  python     80     B    0
3  Jessi       c     85     B    0
4    Tom    java     97     A    0

In [ ]:
print(df.loc[1])

name       Emma
subject    java
score        95
grade         A
etc           0
Name: 1, dtype: object


In [ ]:
df.loc[[0,2,4]]

name subject  score grade  etc
0  Jessi  python    100     A    0
2   Alex  python     80     B    0
4    Tom    java     97     A    0

In [ ]:
row_idx=[1,2,4]
col_idx= ['name', 'subject', 'grade']
df.loc[row_idx, col_idx]

name subject grade
1  Emma    java     A
2  Alex  python     B
4   Tom    java     A

In [ ]:
df.name

0    Jessi
1     Emma
2     Alex
3    Jessi
4      Tom
Name: name, dtype: object

In [ ]:
df.loc[0]=['Jessi','java', 70,'C',1]

In [ ]:
df

name subject  score grade  etc
0  Jessi    java     70     C    1
1   Emma    java     95     A    0
2   Alex  python     80     B    0
3  Jessi       c     85     B    0
4    Tom    java     97     A    0

In [ ]:
score = {'name': ['Jessi', 'Emma', 'Alex', 'Jessi', 'Tom'],
         'score': [100, 95, 80, 85, 97],
         'grade': ['A', 'A', 'B', 'B', 'A'],
         'subject': ['python', 'java', 'python', 'c', 'java']}

c = ['name', 'subject', 'score', 'grade', 'etc']

df = pd.DataFrame(data=score, columns=c)
print(df)

    name subject  score grade  etc
0  Jessi  python    100     A  NaN
1   Emma    java     95     A  NaN
2   Alex  python     80     B  NaN
3  Jessi       c     85     B  NaN
4    Tom    java     97     A  NaN


In [ ]:
semseter_data=pd.Series(['20-01','20-01','20-02','20-01'])
df['semester']=semseter_data
df

name subject  score grade  etc semester
0  Jessi  python    100     A  NaN    20-01
1   Emma    java     95     A  NaN    20-01
2   Alex  python     80     B  NaN    20-02
3  Jessi       c     85     B  NaN    20-01
4    Tom    java     97     A  NaN      NaN

In [ ]:
df['high_score']=df['score']>90
df

name subject  score grade  etc semester  high_score
0  Jessi  python    100     A  NaN    20-01        True
1   Emma    java     95     A  NaN    20-01        True
2   Alex  python     80     B  NaN    20-02       False
3  Jessi       c     85     B  NaN    20-01       False
4    Tom    java     97     A  NaN      NaN        True

In [ ]:
df['score cut1'] = pd.cut(df['score'],
                          bins=[0,70,80,90,100],
                          labels=['D','C','B','A'])

In [ ]:
df

name subject  score grade  etc semester  high_score score cut1
0  Jessi  python    100     A  NaN    20-01        True          A
1   Emma    java     95     A  NaN    20-01        True          A
2   Alex  python     80     B  NaN    20-02       False          C
3  Jessi       c     85     B  NaN    20-01       False          B
4    Tom    java     97     A  NaN      NaN        True          A

In [ ]:
df['score cut2']=np.where(df['score']<=70,'D',
                          np.where(df['score']<=80,'C',
                          np.where(df['score']<=90,'B','A')))

In [ ]:
df

name subject  score grade  etc semester  high_score score cut1 score cut2
0  Jessi  python    100     A  NaN    20-01        True          A          A
1   Emma    java     95     A  NaN    20-01        True          A          A
2   Alex  python     80     B  NaN    20-02       False          C          C
3  Jessi       c     85     B  NaN    20-01       False          B          B
4    Tom    java     97     A  NaN      NaN        True          A          A

2025.02.25

----

In [ ]:
df.loc[6] = ['Jina', 'python', 100,'A', 1, '20-02', True]

In [ ]:
df

name subject  score grade  etc semester  high_score
0  Jessi  python    100     A  NaN    20-01        True
1   Emma    java     95     A  NaN    20-01        True
2   Alex  python     80     B  NaN    20-02       False
3  Jessi       c     85     B  NaN    20-01       False
4    Tom    java     97     A  NaN      NaN        True
6   Jina  python    100     A    1    20-02        True

In [ ]:
df_drop =df.drop(6)

In [ ]:
df_drop

name subject  score grade  etc semester  high_score
0  Jessi  python    100     A  NaN    20-01        True
1   Emma    java     95     A  NaN    20-01        True
2   Alex  python     80     B  NaN    20-02       False
3  Jessi       c     85     B  NaN    20-01       False
4    Tom    java     97     A  NaN      NaN        True

In [ ]:
df.drop(6, inplace=True)

In [ ]:
df.drop(columns=['etc'], inplace=True)

In [ ]:
df

name subject  score grade semester  high_score
0  Jessi  python    100     A    20-01        True
1   Emma    java     95     A    20-01        True
2   Alex  python     80     B    20-02       False
3  Jessi       c     85     B    20-01       False
4    Tom    java     97     A      NaN        True

In [ ]:
df = pd.DataFrame(data = np.arange(18).reshape(6,3),
                  index = ['a','b','c','d','e','f'],
                  columns = ['col1','col2','col3'])

df['col4'] = pd.Series(data = [1.7, 1.2, 2.4],
                       index = ['a','e','c'])
df.loc['c']=None

In [ ]:
df

col1  col2  col3  col4
a   0.0   1.0   2.0   1.7
b   3.0   4.0   5.0   NaN
c   NaN   NaN   NaN   NaN
d   9.0  10.0  11.0   NaN
e  12.0  13.0  14.0   1.2
f  15.0  16.0  17.0   NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, a to f
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    5 non-null      float64
 1   col2    5 non-null      float64
 2   col3    5 non-null      float64
 3   col4    2 non-null      float64
dtypes: float64(4)
memory usage: 412.0+ bytes


In [ ]:
df.isnull()


col1   col2   col3   col4
a  False  False  False  False
b  False  False  False   True
c   True   True   True   True
d  False  False  False   True
e  False  False  False  False
f  False  False  False   True

In [ ]:
df.isnull().sum(axis=1)

a    0
b    1
c    4
d    1
e    0
f    1
dtype: int64

In [ ]:
df.isnull().sum(axis=0)

col1    1
col2    1
col3    1
col4    4
dtype: int64

In [ ]:
df.dropna()

col1  col2  col3  col4
a   0.0   1.0   2.0   1.7
e  12.0  13.0  14.0   1.2

In [ ]:
df.dropna(how='all',inplace=True)
df

col1  col2  col3  col4
a   0.0   1.0   2.0   1.7
b   3.0   4.0   5.0   NaN
d   9.0  10.0  11.0   NaN
e  12.0  13.0  14.0   1.2
f  15.0  16.0  17.0   NaN

In [ ]:
df.dropna(axis=0)

col1  col2  col3  col4
a   0.0   1.0   2.0   1.7
e  12.0  13.0  14.0   1.2

In [ ]:
df.dropna(axis='index')

col1  col2  col3  col4
a   0.0   1.0   2.0   1.7
e  12.0  13.0  14.0   1.2

In [ ]:
df.dropna(axis=1)

col1  col2  col3
a   0.0   1.0   2.0
b   3.0   4.0   5.0
d   9.0  10.0  11.0
e  12.0  13.0  14.0
f  15.0  16.0  17.0

In [ ]:
df.dropna(axis='columns')

col1  col2  col3
a   0.0   1.0   2.0
b   3.0   4.0   5.0
d   9.0  10.0  11.0
e  12.0  13.0  14.0
f  15.0  16.0  17.0

In [ ]:
df.iloc[:2,0]=np.nan
df.iloc[:4,1]=np.nan
df

col1  col2  col3  col4
a   NaN   NaN   2.0   1.7
b   NaN   NaN   5.0   NaN
d   9.0   NaN  11.0   NaN
e  12.0   NaN  14.0   1.2
f  15.0  16.0  17.0   NaN

In [ ]:
df.fillna(0)

col1  col2  col3  col4
a   0.0   0.0   2.0   1.7
b   0.0   0.0   5.0   0.0
d   9.0   0.0  11.0   0.0
e  12.0   0.0  14.0   1.2
f  15.0  16.0  17.0   0.0

In [ ]:
col_fill = {
    'col1' : 5,
    'col2' : 10,
    'col3' : 15,
    'col4' : 20
}

df.fillna(col_fill)

col1  col2  col3  col4
a   5.0  10.0   2.0   1.7
b   5.0  10.0   5.0  20.0
d   9.0  10.0  11.0  20.0
e  12.0  10.0  14.0   1.2
f  15.0  16.0  17.0  20.0

2025.02.26

--------