#0. lib, 데이터 로드

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
src_path = 'https://codepresso-online-platform-public.s3.ap-northeast-2.amazonaws.com/learning-resourse/python_da/accident.txt'
df = pd.read_csv(src_path, sep='\t')

In [3]:
df.head(3)

seq sex serious_yn  age
0    1   M          N    3
1    2   M          N    6
2    3   M          N    4

#1. one-way x-test

* 실제 ~ 기대도수 차이 검정

* 검정과정 : 빈도교차표 -> 기대도수 -> 카이제곱 통계량 산출

---
* 문제
  * 기존 교통사고의 심각여부 남성의 경우 20,30,40,50,60 대 각각의 비율이 10%, 20%, 20%, 30%, 30%로 나타남
* 가설
  * H0 : 기존이 맞다
  * H1 : 기존이 아니다

In [4]:
serious_df = df.loc[df['serious_yn']=='Y']

1. 빈도 교차표

In [10]:
X = pd.crosstab(serious_df['sex'], serious_df['age'], margins=True)
X

age   2   3   4   5   6  All
sex                         
F     3   3   4   5   6   21
M    12  11  17  19  21   80
All  15  14  21  24  27  101

In [8]:
print(X.values)

[[  3   3   4   5   6  21]
 [ 12  11  17  19  21  80]
 [ 15  14  21  24  27 101]]


In [13]:
m = X.values[1, :5]
m

array([12, 11, 17, 19, 21])

---
다른방법

In [14]:
serious_df_male = serious_df.loc[serious_df['sex']=='M']

In [17]:
XX = pd.crosstab(serious_df_male['age'], serious_df_male['serious_yn'], margins=True)
XX.values

array([[12, 12],
       [11, 11],
       [17, 17],
       [19, 19],
       [21, 21],
       [80, 80]])

In [19]:
mm=XX.values[:5,0]
print(mm)

[12 11 17 19 21]


----
2. 기대도수

In [35]:
# 기존 사실
Pr = np.array([0.1,0.2,0.2,0.3,0.2])

In [36]:
n = X.values[1,5]
n

80

In [37]:
E = Pr*n
E

array([ 8., 16., 16., 24., 16.])

3. 검증

In [38]:
stats.chisquare(f_obs=m, f_exp=E)

Power_divergenceResult(statistic=6.229166666666667, pvalue=0.1826751646641975)

#2. two-way x-test

* 두개 범주형 변수 간 연관성 검정

* 검정과정 : 빈도교차표 -> 기대도수 -> 카이제곱 통계량 산출

---
* 문제
  * 교통사고 심각여부 ~ 성별 연관성 유무
* 가설
  * H0 : 연관성 없다
  * H1 : 연관성 있다

1. 빈도교차표

In [39]:
X = pd.crosstab(df['sex'], df['serious_yn'], margins=True)
X

serious_yn    N    Y   All
sex                       
F           296   21   317
M           670   80   750
All         966  101  1067

2. 기대도수 & 3. 카이제곱 검정
two-way x-test는 2,3을 동시에 해줌

In [40]:
m = X.values[:2,:2]

In [41]:
stats.chi2_contingency(m)

Chi2ContingencyResult(statistic=3.7895026717172966, pvalue=0.051574970410524265, dof=1, expected_freq=array([[286.99343955,  30.00656045],
       [679.00656045,  70.99343955]]))