In [ ]:
import numpy as np

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [11]:
cd /content/drive/MyDrive/learnerton/Github

/content/drive/MyDrive/learnerton/Github


In [13]:
!git clone https://dongdaran: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@github.com/dongdaran/learnerton.git

Cloning into 'learnerton'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.


In [14]:
cd learnerton/

/content/drive/MyDrive/learnerton/Github/learnerton


In [15]:
!git config --global user.email 'essibae5@naver.com'
!git config --global user.name 'dongdaran'

In [ ]:
print(np.__version__)

1.26.4


In [ ]:
data = [10,20,30]
arr = np.array(data)

print("1D ndarray : ")
print(arr)
print("type : ", type(arr))
print("shape : {}, size : {}, dtype : {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))

1D ndarray : 
[10 20 30]
type :  <class 'numpy.ndarray'>
shape : (3,), size : 3, dtype : int64, dimension: 1


In [ ]:
data = [[1,2,3], [4,5,6]]
arr = np.array(data)

print("2D ndarray : ")
print(arr)
print("type : ", type(arr))
print("shape : {}, size : {}, dtype : {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))

2D ndarray : 
[[1 2 3]
 [4 5 6]]
type :  <class 'numpy.ndarray'>
shape : (2, 3), size : 6, dtype : int64, dimension: 2


In [ ]:
data = [[1,2,3], [4,5,6]]
arr = np.array(data, dtype = float)

print("2D ndarray : ")
print(arr)
print("type : ", type(arr))
print("shape : {}, size : {}, dtype : {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))

2D ndarray : 
[[1. 2. 3.]
 [4. 5. 6.]]
type :  <class 'numpy.ndarray'>
shape : (2, 3), size : 6, dtype : float64, dimension: 2


In [ ]:
data = [[[1,2,3],[4,5,6]],[[3,2,1],[4,5,6]]]
arr = np.array(data)

print("2D ndarray : ")
print(arr)
print("type : ", type(arr))
print("shape : {}, size : {}, dtype : {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))

2D ndarray : 
[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [4 5 6]]]
type :  <class 'numpy.ndarray'>
shape : (2, 2, 3), size : 12, dtype : int64, dimension: 3


In [ ]:
print(np.arange(2,10))
print(np.arange(2,10,2))
print(np.arange(10))

[2 3 4 5 6 7 8 9]
[2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
np.zeros(5)
np.zeros((2,10))
np.zeros((2,4,5), dtype =int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [ ]:
np.full((3,4),77,dtype=float)

array([[77., 77., 77., 77.],
       [77., 77., 77., 77.],
       [77., 77., 77., 77.]])

In [ ]:
np.empty((2,2))

array([[1.e-323, 2.e-323],
       [3.e-323, 4.e-323]])

In [ ]:
data = [[1,2,3],[4,5,6]]
sample = np.array(data)

one_array = np.ones_like(sample)

print("<sample>")
print(sample)
print()
print("<one_array>")
print(one_array)

<sample>
[[1 2 3]
 [4 5 6]]

<one_array>
[[1 1 1]
 [1 1 1]]


In [ ]:
origin = np.arange(1,2, 0.2)
change = origin.astype(int)

print("<origin>")
print(origin)
print()
print("<change>")
print(change)

<origin>
[1.  1.2 1.4 1.6 1.8]

<change>
[1 1 1 1 1]


In [ ]:
origin =np.arange(15)
reshape_arr1 = np.reshape(origin, (3,5))
reshape_arr2 = origin.reshape((3,5))
print("<origin>")
print(origin)
print()
print("<reshape_arr1>")
print(reshape_arr1)
print()
print("<reshape_arr2>")
print(reshape_arr2)

<origin>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

<reshape_arr1>
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

<reshape_arr2>
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
origin =np.arange(15)
reshape_arr = np.reshape(origin, (-1,1))

print("<origin>")
print(origin)
print()
print("<reshape_arr>")
print(reshape_arr)
print()

<origin>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

<reshape_arr>
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]



In [ ]:
A = np.arange(1,10).reshape(3,3)
B = np.sort(np.arange(1,10))[::-1].reshape(3,3)

print("A--")
print(A)
print()
print("B--")
print(B)
print()
print("result of A>B--")
print(A>B)

A--
[[1 2 3]
 [4 5 6]
 [7 8 9]]

B--
[[9 8 7]
 [6 5 4]
 [3 2 1]]

result of A>B--
[[False False False]
 [False False  True]
 [ True  True  True]]


In [ ]:
sample = np.arange(16).reshape(4,2,2)
print(sample)
print()
print("index (1,1,1) :" ,sample[1,1,1])

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]

index (1,1,1) : 7


In [ ]:
sample = np.arange(1,17).reshape(4,4)
print("<all>")
print(sample)
print()
print("<[:,1:-1]>")
print(sample[:,1:-1])
print()
print("<[:-1,2]>")
print(sample[:-1,2])
print()
print("<[:,-1]>")
print(sample[:,-1])

<all>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

<[:,1:-1]>
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

<[:-1,2]>
[ 3  7 11]

<[:,-1]>
[ 4  8 12 16]


In [ ]:
name = np.array(['John', 'Samuel', 'Kate', 'Mike', 'Sarah'])
score = np.array([78, 84, 96, 88, 82])

sort_indexes = np.argsort(score)[::-1]
print("sort indexes : ", sort_indexes)
print("sort values : ", name[sort_indexes])

sort indexes :  [2 3 1 4 0]
sort values :  ['Kate' 'Mike' 'Samuel' 'Sarah' 'John']


In [ ]:
from google.colab import drive
drive.mount('/content/drive')