In [20]:
import torch
import numpy as np

#Pytorch tensor 생성

In [ ]:
#(2, 2, 3) shape의 tensor 생성
d3_tensor = torch.tensor([[[1,2,3],
                            [4,5,6]],
                          [[-1,-2,-3],
                           [-4,-5,-6]]])

In [ ]:
d3_tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[-1, -2, -3],
         [-4, -5, -6]]])

In [ ]:
print(d3_tensor.ndim)
print(d3_tensor.shape)
print(d3_tensor.dtype)

3
torch.Size([2, 2, 3])
torch.int64


# PyTorch API를 이용한 텐서의 생성

In [ ]:
# shape = (2, 2, 3) 인 values = 0
torch.zeros(size=(2,2,3))

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

np array 이용방법

In [ ]:
import numpy as np

In [ ]:
d3_np_tensor = np.array([[[1,2,3],
                            [4,5,6]],
                          [[-1,-2,-3],
                           [-4,-5,-6]]])

In [ ]:
d3_torch_tensor1 = torch.Tensor(d3_np_tensor)

In [ ]:
print(d3_np_tensor)
print(d3_torch_tensor1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[-1., -2., -3.],
         [-4., -5., -6.]]])


In [ ]:
d3_torch_tensor2 = torch.from_numpy(d3_np_tensor)

In [ ]:
print(d3_np_tensor)
print(d3_torch_tensor2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[-1, -2, -3],
         [-4, -5, -6]]])


# Pytorch 수학연산

* pytorch 덧셈, 뺄셈, 곱셈, 나눗셈은 shape이 동일해야 한다.

* .T transform method

In [3]:
tensor_a = torch.tensor([[1,2,3],
                         [4,5,6]])
tensor_b = torch.tensor([[-1,-2,-3],
                         [-4,-5,-6]])

In [ ]:
torch.matmul(tensor_a, tensor_b.T)

tensor([[-14, -32],
        [-32, -77]])

In [7]:
tensor_axis_max = torch.max(tensor_a, axis = 1)

In [8]:
tensor_axis_max

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))

In [9]:
tensor_axis_max[0]

tensor([3, 6])

미분(역전파)
-tensor_x 값이 tensor_z 값에 미치는 영향도(미분값)

In [11]:
tensor_x = torch.tensor([[1., 2., 3.],
                        [4., 5., 6.]], requires_grad= True)

tensor_y = torch.tensor([[7., 8., 9.],
                        [10., 11., 12.]], requires_grad= True)

In [12]:
tensor_z = torch.square(tensor_x + tensor_y)

In [16]:
tensor_z.sum().backward()

In [17]:
gradient_zx = tensor_x.grad

In [21]:
print(np.round(gradient_zx, 2))

tensor([[16., 20., 24.],
        [28., 32., 36.]])
